const books = [
  {
    id: 1,
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    price: 15.99,
    image: 'https://source.unsplash.com/featured/?gatsby',
  },
  {
    id: 2,
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    price: 12.99,
    image: 'https://source.unsplash.com/featured/?mockingbird',
  },
  {
    id: 3,
    title: '1984',
    author: 'George Orwell',
    price: 10.99,
    image: 'https://source.unsplash.com/featured/?1984',
  },
  {
    id: 4,
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    price: 14.99,
    image: 'https://source.unsplash.com/featured/?pride-prejudice',
  },
  {
    id: 5,
    title: 'The Catcher in the Rye',
    author: 'J.D. Salinger',
    price: 11.99,
    image: 'https://source.unsplash.com/featured/?catcher-rye',
  },
  {
    id: 6,
    title: 'One Hundred Years of Solitude',
    author: 'Gabriel García Márquez',
    price: 13.99,
    image: 'https://source.unsplash.com/featured/?solitude',
  },
  {
    id: 7,
    title: 'The Hobbit',
    author: 'J.R.R. Tolkien',
    price: 16.99,
    image: 'https://source.unsplash.com/featured/?hobbit',
  },
  {
    id: 8,
    title: 'Brave New World',
    author: 'Aldous Huxley',
    price: 12.99,
    image: 'https://source.unsplash.com/featured/?brave-new-world',
  },
  {
    id: 9,
    title: 'Moby-Dick',
    author: 'Herman Melville',
    price: 15.99,
    image: 'https://source.unsplash.com/featured/?moby-dick',
  },
  {
    id: 10,
    title: 'The Odyssey',
    author: 'Homer',
    price: 14.99,
    image: 'https://source.unsplash.com/featured/?odyssey',
  },
  {
    id: 11,
    title: 'The Lord of the Rings',
    author: 'J.R.R. Tolkien',
    price: 19.99,
    image: 'https://source.unsplash.com/featured/?lord-of-the-rings',
  },
  {
    id: 12,
    title: 'Fahrenheit 451',
    author: 'Ray Bradbury',
    price: 11.99,
    image: 'https://source.unsplash.com/featured/?fahrenheit-451',
  },
  {
    id: 13,
    title: 'The Chronicles of Narnia',
    author: 'C.S. Lewis',
    price: 17.99,
    image: 'https://source.unsplash.com/featured/?narnia',
  },
  {
    id: 14,
    title: 'Frankenstein',
    author: 'Mary Shelley',
    price: 13.99,
    image: 'https://source.unsplash.com/featured/?frankenstein',
  },
  {
    id: 15,
    title: 'The Color Purple',
    author: 'Alice Walker',
    price: 14.99,
    image: 'https://source.unsplash.com/featured/?color-purple',
  },
  {
    id: 16,
    title: 'The Shining',
    author: 'Stephen King',
    price: 16.99,
    image: 'https://source.unsplash.com/featured/?the-shining',
  },
  {
    id: 17,
    title: 'Sapiens: A Brief History of Humankind',
    author: 'Yuval Noah Harari',
    price: 18.99,
    image: 'https://source.unsplash.com/featured/?sapiens',
  },
  {
    id: 18,
    title: 'Wuthering Heights',
    author: 'Emily Brontë',
    price: 12.99,
    image: 'https://source.unsplash.com/featured/?wuthering-heights',
  },
  {
    id: 19,
    title: 'The Alchemist',
    author: 'Paulo Coelho',
    price: 15.99,
    image: 'https://source.unsplash.com/featured/?alchemist',
  },
  {
    id: 20,
    title: 'The Hitchhiker\'s Guide to the Galaxy',
    author: 'Douglas Adams',
    price: 14.99,
    image: 'https://source.unsplash.com/featured/?hitchhikers-guide',
  },
  {
    id: 21,
    title: 'The Road',
    author: 'Cormac McCarthy',
    price: 14.99,
    image: 'https://source.unsplash.com/featured/?the-road',
  },
  {
    id: 22,
    title: 'The Handmaid\'s Tale',
    author: 'Margaret Atwood',
    price: 16.99,
    image: 'https://source.unsplash.com/featured/?handmaids-tale',
  },
  {
    id: 23,
    title: 'The Stranger',
    author: 'Albert Camus',
    price: 12.99,
    image: 'https://source.unsplash.com/featured/?the-stranger',
  },
  {
    id: 24,
    title: 'The Grapes of Wrath',
    author: 'John Steinbeck',
    price: 15.99,
    image: 'https://source.unsplash.com/featured/?grapes-of-wrath',
  },
  {
    id: 25,
    title: 'The Count of Monte Cristo',
    author: 'Alexandre Dumas',
    price: 18.99,
    image: 'https://source.unsplash.com/featured/?monte-cristo',
  },
  {
    id: 26,
    title: 'The Picture of Dorian Gray',
    author: 'Oscar Wilde',
    price: 13.99,
    image: 'https://source.unsplash.com/featured/?dorian-gray',
  },
  {
    id: 27,
    title: 'A Tale of Two Cities',
    author: 'Charles Dickens',
    price: 14.99,
    image: 'https://source.unsplash.com/featured/?tale-of-two-cities',
  },
  {
    id: 28,
    title: 'Crime and Punishment',
    author: 'Fyodor Dostoevsky',
    price: 17.99,
    image: 'https://source.unsplash.com/featured/?crime-and-punishment',
  },
  {
    id: 29,
    title: 'Great Expectations',
    author: 'Charles Dickens',
    price: 15.99,
    image: 'https://source.unsplash.com/featured/?great-expectations',
  },
  {
    id: 30,
    title: 'The Silent Patient',
    author: 'Alex Michaelides',
    price: 19.99,
    image: 'https://source.unsplash.com/featured/?silent-patient',
  },
  {
    id: 31,
    title: 'The Book Thief',
    author: 'Markus Zusak',
    price: 16.99,
    image: 'https://source.unsplash.com/featured/?book-thief',
  },
  {
    id: 32,
    title: 'The Martian',
    author: 'Andy Weir',
    price: 14.99,
    image: 'https://source.unsplash.com/featured/?the-martian',
  },
];

module.exports = books;